[project]
name = "gxhash"
description = "Python bindings for GxHash"
readme = "README.md"
license = "MIT"
requires-python = ">=3.8"
dynamic = ["version"]
keywords = ["hash"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]

[project.urls]
Homepage = "https://github.com/winstxnhdw/gxhash"
Documentation = "https://github.com/winstxnhdw/gxhash"
Repository = "https://github.com/winstxnhdw/gxhash"
Issues = "https://github.com/winstxnhdw/gxhash/issues"

[dependency-groups]
dev = ["commitizen>=3.31.0", "maturin>=1.10.2", "pyright>=1.1.407", "ruff>=0.14.6"]

[build-system]
requires = ["maturin>=1.10.2, <2.0.0"]
build-backend = "maturin"

[tool.maturin]
profile = "release"
locked = true
strip = true
features = ["pyo3/extension-module"]
exclude = [".github/**/*", "**/uv.lock", "**/Makefile", "**/.gitgnore", "**/rustfmt.toml"]

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = ["ALL"]
ignore = ["PYI021", "A002", "COM812", "D203", "D205", "D211", "D212", "D400", "D413", "D415", "D417"]

[tool.pyright]
typeCheckingMode = "strict"

[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "$version"
version_scheme = "pep440"
version_provider = "cargo"
update_changelog_on_bump = true
major_version_zero = true
