name: Clippy

on:
  pull_request:
  push:
    paths:
      - .github/workflows/clippy.yml
      - Cargo.toml
      - "**/*.rs"

jobs:
  clippy:
    uses: winstxnhdw/actions/.github/workflows/clippy.yml@main
