name: Lint

on:
  workflow_call:
  pull_request:
  push:
    paths:
      - .github/workflows/clippy.yml
      - "**/Cargo.toml"
      - "**/Cargo.lock"
      - "**.rs"

permissions: {}
env:
  RUSTFLAGS: -C target-feature=+aes,+ssse3

jobs:
  clippy:
    strategy:
      matrix:
        working-directory: [., bench, perf, tests]

    uses: winstxnhdw/actions/.github/workflows/rust.yml@main
    with:
      disable-test: true
      working-directory: ${{ matrix.working-directory }}

  lint:
    if: always()
    needs: clippy
    runs-on: ubuntu-slim

    steps:
      - name: Fail if any dependency failed or was cancelled
        if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
        run: exit 1
