name: Format

on:
  pull_request:
    paths:
      - .github/workflows/formatter.yml
      - "**/pyproject.toml"
      - "**/uv.lock"
      - "**.py"
      - "**.pyi"

permissions:
  contents: write

jobs:
  format:
    uses: winstxnhdw/actions/.github/workflows/format-python.yml@main
