name: Lint

on:
  pull_request:
    types: [opened]
  push:
    paths:
      - gxhash/**
      - .github/workflows/lint.yml
      - Cargo.toml
      - pyproject.toml
      - "**.rs"
      - "**.py"

jobs:
  clippy:
    strategy:
      matrix:
        working-directory: [., bench]

    uses: winstxnhdw/actions/.github/workflows/rust.yml@main
    with:
      disable-test: true
      working-directory: ${{ matrix.working-directory }}

  typecheck:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - 3.8
          - 3.9
          - "3.10"
          - 3.11
          - 3.12
          - 3.13
          - 3.14

    env:
      UV_LOCKED: 1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2
        with:
          show-progress: false

      - name: Install uv
        uses: astral-sh/setup-uv@v7.3.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run type checker
        run: uv run pyright

  lint:
    if: always()
    needs: [clippy, typecheck]
    runs-on: ubuntu-latest

    steps:
      - name: Fail if any dependency failed or was cancelled
        if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
        run: exit 1
