name: Lint

on:
  pull_request:
  push:
    paths:
      - .github/workflows/lint.yml
      - Cargo.toml
      - "**.rs"
      - "**.py"

jobs:
  clippy:
    uses: winstxnhdw/actions/.github/workflows/clippy.yml@main

  typecheck:
    runs-on: ubuntu-latest
    env:
      UV_LOCKED: 1
    strategy:
      matrix:
        python-version: [3.8, 3.9, "3.10", 3.11, 3.12, 3.13, 3.13t, 3.14, 3.14t]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.1
        with:
          show-progress: false

      - name: Install uv
        uses: astral-sh/setup-uv@v7.2.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: uv sync --no-install-project

      - name: Run type checker
        run: uv run --no-project pyright

  lint:
    needs: [clippy, typecheck]
    runs-on: ubuntu-latest

    steps:
      - name: Lint completed
        run: echo "All linting jobs completed successfully."
