name: Build

on:
  workflow_call:
  pull_request:
  push:
    paths:
      - .github/workflows/main.yml
      - uv.lock
      - pyproject.toml
      - Cargo.toml
      - Cargo.lock
      - rust-toolchain.toml
      - src/**
      - tests/**.rs
      - build.rs
      - "!bench/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  install:
    runs-on: ${{ matrix.runs-on }}
    strategy:
      matrix:
        python-version:
          - 3.8
          - 3.9
          - "3.10"
          - 3.11
          - pypy3.11
          - 3.12
          - 3.13
          - 3.13t
          - 3.14
          - 3.14t
        runs-on:
          - ubuntu-latest
          - ubuntu-24.04-arm
          - macos-latest
          - macos-15-intel
          - windows-latest
        include:
          - runs-on: ubuntu-latest
            maturin-pep517-args: "--features hybrid"

          - runs-on: ubuntu-24.04-arm
            maturin-pep517-args: ""

          - runs-on: macos-latest
            maturin-pep517-args: ""
            rustflags: "-C target-feature=+aes,+neon"

          - runs-on: macos-15-intel
            maturin-pep517-args: "--features hybrid"

          - runs-on: windows-latest
            maturin-pep517-args: "--features hybrid"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2
        with:
          show-progress: false

      - name: Uninstall Rust
        if: ${{  matrix.runs-on != 'windows-latest' && matrix.python-version != 3.8 && matrix.python-version != 'pypy3.11' }}
        run: rustup self uninstall -y || brew uninstall rustup

      - name: Install uv
        uses: astral-sh/setup-uv@v7.3.0
        with:
          python-version: ${{ matrix.python-version }}
          activate-environment: true

      - name: Set RUSTFLAGS
        if: matrix.rustflags
        run: echo "RUSTFLAGS=${{ matrix.rustflags }}" >> $GITHUB_ENV

      - name: Install project
        run: uv pip install .
        env:
          MATURIN_PEP517_ARGS: ${{ matrix.maturin-pep517-args }}

  test:
    runs-on: ${{ matrix.runs-on }}
    strategy:
      matrix:
        python-version:
          - 3.8
          - 3.9
          - "3.10"
          - 3.11
          - 3.12
          - 3.13
          - 3.13t
          - 3.14
          - 3.14t
        runs-on:
          - ubuntu-latest
          - ubuntu-24.04-arm
          - macos-latest
          - macos-15-intel
          - windows-latest
        include:
          - runs-on: ubuntu-latest
            rustflags: "-C target-feature=+aes,+sse2"

          - runs-on: ubuntu-24.04-arm
            rustflags: "-C target-feature=+aes,+neon"

          - runs-on: macos-latest
            rustflags: "-C target-feature=+aes,+neon"

          - runs-on: macos-15-intel
            rustflags: "-C target-feature=+aes,+sse2"

          - runs-on: windows-latest
            rustflags: "-C target-feature=+aes,+sse2"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2
        with:
          show-progress: false

      - name: Cache Cargo
        uses: actions/cache@v5.0.3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ matrix.runs-on }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Setup Python
        uses: actions/setup-python@v6.2.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Test
        run: cargo test
        env:
          RUSTFLAGS: ${{ matrix.rustflags }}

  coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2
        with:
          show-progress: false

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov

      - name: Generate code coverage
        run: cargo llvm-cov --all-features --workspace --lcov --output-path lcov.info

      - name: Upload code coverage report
        uses: actions/upload-artifact@v6.0.0
        with:
          name: coverage
          path: lcov.info

  report:
    needs: [install, test, coverage]
    runs-on: ubuntu-latest

    steps:
      - name: Upload code coverage report
        uses: actions/download-artifact@v6.0.0
        with:
          pattern: coverage
          path: lcov.info

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5.5.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: lcov.info
          fail_ci_if_error: true
