name: Build

on:
  workflow_call:
  pull_request:
  push:
    paths:
      - .github/workflows/main.yml
      - pyproject.toml
      - uv.lock
      - Cargo.toml
      - Cargo.lock
      - rust-toolchain.toml
      - build.rs
      - src/**
      - tests/**.rs
      - "!bench/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  install:
    runs-on: ${{ matrix.runs-on }}
    strategy:
      matrix:
        python-version:
          - 3.8
          - 3.9
          - "3.10"
          - 3.11
          - 3.12
          - 3.13
          - 3.13t
          - 3.14
          - 3.14t

        runs-on:
          - ubuntu-latest
          - ubuntu-24.04-arm
          - macos-latest
          - macos-15-intel
          - windows-latest
          - windows-11-arm

        exclude:
          - runs-on: windows-11-arm
            python-version: 3.8

          - runs-on: windows-11-arm
            python-version: 3.9

          - runs-on: windows-11-arm
            python-version: "3.10"

        include:
          - runs-on: ubuntu-latest
            maturin-pep517-args: "--features hybrid"
            arch: x86_64

          - runs-on: ubuntu-24.04-arm
            maturin-pep517-args: ""
            arch: arm64

          - runs-on: macos-latest
            maturin-pep517-args: ""
            arch: arm64

          - runs-on: macos-15-intel
            maturin-pep517-args: "--features hybrid"
            arch: x86_64

          - runs-on: windows-latest
            maturin-pep517-args: "--features hybrid"
            arch: x86_64

          - runs-on: windows-11-arm
            maturin-pep517-args: ""
            arch: arm64

    env:
      UV_LOCKED: 1
      UV_NO_DEV: 1
      MATURIN_PEP517_ARGS: ${{ matrix.maturin-pep517-args }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2
        with:
          show-progress: false

      - name: Uninstall Rust
        if: runner.os != 'Windows' && matrix.python-version != 3.8 && matrix.python-version != 'pypy3.11'
        run: rustup self uninstall -y || brew uninstall rustup

      - name: Install uv
        uses: astral-sh/setup-uv@v7.3.0
        with:
          python-version: ${{ matrix.python-version }}-${{ matrix.arch }}
          activate-environment: true

      - name: Build sdist
        run: uv build --sdist

      - name: Install project
        shell: bash
        run: uv pip install dist/gxhash-*.tar.gz

  test:
    runs-on: ${{ matrix.runs-on }}
    strategy:
      matrix:
        python-version:
          - 3.8
          - 3.9
          - "3.10"
          - 3.11
          - 3.12
          - 3.13
          - 3.13t
          - 3.14
          - 3.14t
        runs-on:
          - ubuntu-latest
          - ubuntu-24.04-arm
          - macos-latest
          - macos-15-intel
          - windows-latest
          - windows-11-arm

        exclude:
          - runs-on: windows-11-arm
            python-version: 3.8

          - runs-on: windows-11-arm
            python-version: 3.9

          - runs-on: windows-11-arm
            python-version: "3.10"

        include:
          - runs-on: ubuntu-latest
            arch: x64

          - runs-on: ubuntu-24.04-arm
            arch: arm64

          - runs-on: macos-latest
            arch: arm64

          - runs-on: macos-15-intel
            arch: x64

          - runs-on: windows-latest
            arch: x64

          - runs-on: windows-11-arm
            arch: arm64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2
        with:
          show-progress: false

      - name: Setup Python
        uses: actions/setup-python@v6.2.0
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.arch }}

      - name: Test
        run: cargo test

  coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2
        with:
          show-progress: false

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov

      - name: Generate code coverage
        run: cargo llvm-cov --all-features --workspace --lcov --output-path lcov.info

      - name: Upload code coverage report
        uses: actions/upload-artifact@v6.0.0
        with:
          name: coverage
          path: lcov.info

  report:
    if: always()
    needs: [install, test, coverage]
    runs-on: ubuntu-slim

    steps:
      - name: Fail if any dependency failed or was cancelled
        if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
        run: exit 1

      - name: Upload code coverage report
        uses: actions/download-artifact@v7.0.0
        with:
          pattern: coverage
          path: lcov.info

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5.5.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: lcov.info
          fail_ci_if_error: true
