name: Performance

on:
  pull_request:
  push:
    paths:
      - .github/workflows/performance.yml
      - Cargo.toml
      - Cargo.lock
      - rust-toolchain.toml
      - src/**
      - perf/**
      - "!bench/**"

env:
  RUSTFLAGS: -C target-feature=+aes,+ssse3

jobs:
  performance:
    if: github.actor != 'renovate[bot]'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2
        with:
          show-progress: false

      - name: Setup Python
        uses: actions/setup-python@v6.2.0
        with:
          python-version: 3.14.3

      - name: Install cargo-codspeed
        uses: taiki-e/install-action@v2.68.4
        with:
          tool: cargo-codspeed

      - name: Build the benchmark target
        run: cargo codspeed build

      - name: Run the benchmark simulation
        uses: CodSpeedHQ/action@v4.10.6
        with:
          mode: simulation
          run: cargo codspeed run
