name: Performance

on:
  pull_request:
  push:
    branches: [main]
    paths:
      - .github/workflows/performance.yml
      - Cargo.toml
      - Cargo.lock
      - src/**
      - "!bench/**"
jobs:
  performance:
    if: github.actor != 'renovate[bot]'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2
        with:
          show-progress: false

      - name: Setup Python
        uses: actions/setup-python@v6.2.0
        with:
          python-version: 3.14

      - name: Cache Cargo
        uses: actions/cache@v5.0.2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install cargo-codspeed
        uses: taiki-e/install-action@v2.67.15
        with:
          tool: cargo-codspeed

      - name: Build the benchmark target
        run: cargo codspeed build
        env:
          RUSTFLAGS: "-C target-cpu=native"

      - name: Run the benchmark simulation
        uses: CodSpeedHQ/action@v4.10.0
        with:
          mode: simulation
          run: cargo codspeed run
