name: Release

on:
  workflow_dispatch:
    inputs:
      release-type:
        description: Release Type
        type: choice
        default: patch
        options: [patch, minor, major]

permissions: {}

jobs:
  main:
    uses: winstxnhdw/gxhash/.github/workflows/main.yml@main
    secrets: inherit

  clippy:
    uses: winstxnhdw/gxhash/.github/workflows/clippy.yml@main

  python:
    uses: winstxnhdw/gxhash/.github/workflows/python.yml@main

  release:
    needs: [main, clippy, python]
    runs-on: ubuntu-slim

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2
        with:
          show-progress: false
          fetch-depth: 0
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - name: Install commitizen
        uses: commitizen-tools/setup-cz@v0.7.0

      - name: Get next ${{ inputs.release-type }} revision
        id: get-revision
        run: echo "REVISION=$(cz bump --get-next --increment ${{ inputs.release-type }})" >> $GITHUB_OUTPUT

      - name: Create bump and changelog
        run: |
          cz bump --increment ${{ inputs.release-type }} \
                  --yes \
                  --changelog \
                  --no-verify \
                  --git-output-to-stderr \
                  --changelog-to-stdout | sed '1d' >body.md

      - name: Update lockfiles
        run: |
          cargo update --manifest-path tests/Cargo.toml
          cargo update --manifest-path perf/Cargo.toml

      - name: Push changelog and tag
        run: git push --atomic origin main ${{ steps.get-revision.outputs.REVISION }}

      - name: Create GitHub release ${{ steps.get-revision.outputs.REVISION }}
        id: release
        run: gh release create ${{ steps.get-revision.outputs.REVISION }} -t ${{ steps.get-revision.outputs.REVISION }} -F body.md --verify-tag
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Revert changelog and tag on failure
        if: failure() && steps.release.outcome == 'failure'
        run: |
          git revert HEAD --no-commit
          git commit -m "revert: release ${{ steps.get-revision.outputs.REVISION }}"
          git push --atomic origin main --delete ${{ steps.get-revision.outputs.REVISION }}
