name: Release

on:
  workflow_dispatch:
    inputs:
      release-type:
        description: Release Type
        type: choice
        default: patch
        options:
          - patch
          - minor
          - major

jobs:
  main:
    uses: winstxnhdw/gxhash/.github/workflows/main.yml@main
    secrets: inherit

  release:
    needs: main
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2
        with:
          show-progress: false
          fetch-depth: 0
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - name: Install commitizen
        uses: commitizen-tools/setup-cz@v0.7.0

      - name: Get next revision
        id: get-revision
        run: echo "REVISION=$(cz bump --get-next --increment ${{ inputs.release-type }})" >> $GITHUB_OUTPUT

      - name: Create bump and changelog
        run: |
          cz bump \
              --increment ${{ inputs.release-type }} \
              --yes \
              --changelog \
              --no-verify \
              --git-output-to-stderr \
              --changelog-to-stdout >body.md

      - name: Push
        run: git push --atomic origin main ${{ steps.get-revision.outputs.REVISION }}

      - name: Create GitHub release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          sed -i '1d' body.md
          gh release create ${{ steps.get-revision.outputs.REVISION }} -t ${{ steps.get-revision.outputs.REVISION }} -F body.md --verify-tag
