name: Release

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: Release type.
        type: choice
        default: patch
        options:
          - patch
          - minor
          - major

jobs:
  main:
    uses: ./.github/workflows/main.yml
    secrets: inherit

  release:
    needs: main
    runs-on: ubuntu-latest
    env:
      UV_LOCKED: 1
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.1
        with:
          show-progress: false
          fetch-depth: 0
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@master
        with:
          increment: ${{ github.event.inputs.release_type }}
          changelog_increment_filename: body.md
          push: false

      - name: Set Git config
        run: |
          git config user.email github-actions[bot]@users.noreply.github.com
          git config user.name github-actions[bot]

      - name: Push
        run: |
          git add .
          git commit -m "chore(release): release ${{ env.REVISION }}" --no-verify
          git push --atomic origin main --tags

      - name: Create GitHub release
        run: gh release create ${{ env.REVISION }} -t ${{ env.REVISION }} -F body.md --verify-tag
        env:
          GH_TOKEN: ${{ github.token }}
