name: Release

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: Release Type
        type: choice
        default: patch
        options:
          - patch
          - minor
          - major

jobs:
  main:
    uses: winstxnhdw/gxhash/.github/workflows/main.yml@main
    secrets: inherit

  release:
    needs: main
    runs-on: ubuntu-latest
    env:
      UV_LOCKED: 1
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.1
        with:
          show-progress: false
          fetch-depth: 0
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - name: Install uv
        uses: astral-sh/setup-uv@v7.2.0
        with:
          python-version: ${{ matrix.python-version }}
          activate-environment: true

      - name: Create bump and changelog
        run: |
          uvx --no-cache --from commitizen cz bump \
              --increment ${{ github.event.inputs.release_type }} \
              --yes \
              --changelog \
              --files-only \
              --changelog-to-stdout >body.md

      - name: Set Git config
        run: |
          git config user.email github-actions[bot]@users.noreply.github.com
          git config user.name github-actions[bot]

      - name: Push
        run: |
          git add .
          git restore --staged body.md
          git commit -m "chore(release): release ${{ env.REVISION }}" --no-verify
          git push --atomic origin main --tags

      - name: Create GitHub release
        run: gh release create ${{ env.REVISION }} -t ${{ env.REVISION }} -F body.md --verify-tag
        env:
          GH_TOKEN: ${{ github.token }}
