name: Release

on:
  workflow_dispatch:
    inputs:
      release-type:
        description: Release Type
        type: choice
        default: patch
        options:
          - patch
          - minor
          - major

jobs:
  main:
    uses: winstxnhdw/gxhash/.github/workflows/main.yml@main
    secrets: inherit

  release:
    needs: main
    runs-on: ubuntu-latest
    env:
      UV_LOCKED: 1
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2
        with:
          show-progress: false
          fetch-depth: 0
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - name: Install uv
        uses: astral-sh/setup-uv@v7.2.0
        with:
          python-version: ${{ matrix.python-version }}
          activate-environment: true

      - name: Set Git config
        run: |
          git config user.email github-actions[bot]@users.noreply.github.com
          git config user.name github-actions[bot]

      - name: Get next revision
        id: get-revision
        run: echo "REVISION=$(uvx --from commitizen cz bump --get-next --increment ${{ inputs.release-type }})" >> $GITHUB_ENV

      - name: Create bump and changelog
        run: |
          uvx --from commitizen cz bump \
              --increment ${{ inputs.release-type }} \
              --yes \
              --changelog \
              --no-verify \
              --git-output-to-stderr \
              --changelog-to-stdout >body.md

      - name: Push
        run: |
          git push --atomic --follow-tags

      - name: Create GitHub release
        run: gh release create ${{ steps.get-revision.outputs.REVISION }} -t ${{ steps.get-revision.outputs.REVISION }} -F body.md --verify-tag
        env:
          GH_TOKEN: ${{ github.token }}
